#!/data/data/com.termux/files/usr/bin/sh
# Phone side: ~/git/grafana-dashboards.git/hooks/post-receive. On push: check out, generate, grafana's file provider reloads.
set -e
dst=$HOME/monitoring/dashboards
mkdir -p $dst
git --work-tree=$dst checkout -f master
cd $dst && python3 gen.py
echo "deployed $(git --git-dir=$GIT_DIR rev-parse --short master) -> $dst"
